#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@Time    : 2026/01/12
@Author  : MetaGPT-Pro Team
@File    : daily_standup.py
@Desc    : Daily Standup ceremony action - collects status and identifies blockers
"""
from typing import Dict, List, Optional
from datetime import datetime

from pydantic import Field

from metagpt.actions import Action
from metagpt.logs import logger
from metagpt.project.schemas import Task, TaskStatus, Sprint
from metagpt.project.backlog_manager import BacklogManager
from metagpt.project.board_tracker import board_tracker
from metagpt.schema import Message
from metagpt.tools.tool_registry import register_tool


STANDUP_PROMPT = """
You are facilitating a Daily Standup for the development team.

## Current Sprint Status
{sprint_status}

## Board Status
- TODO: {todo_count} tasks
- In Progress: {in_progress_count} tasks
- Review: {review_count} tasks
- Done: {done_count} tasks
- Blocked: {blocked_count} tasks

## Blocked Tasks
{blocked_details}

## Recently Completed
{completed_details}

Based on this information, provide:
1. A brief summary of sprint progress
2. Key blockers that need attention
3. Recommendations for the team

Format your response as a standup report.
"""


@register_tool(include_functions=["run"])
class DailyStandupAction(Action):
    """Conducts Daily Standup ceremony to track progress and identify blockers"""
    
    name: str = "DailyStandup"
    desc: str = "Conduct Daily Standup to collect status and identify blockers"
    
    async def run(
        self,
        project_id: str,
        team_status: Optional[Dict[str, str]] = None,
        **kwargs
    ) -> Message:
        """
        Conduct Daily Standup ceremony.
        
        Args:
            project_id: The project identifier
            team_status: Optional dict of agent names to their status updates
            
        Returns:
            Message containing standup summary
        """
        logger.info(f"Starting Daily Standup for project {project_id}")
        
        # Get board state
        board = board_tracker.get_board(project_id)
        tasks = board_tracker.get_tasks(project_id)
        
        if not board:
            # Try to load from disk
            board = await board_tracker.load_board(project_id)
            if not board:
                return Message(
                    content="No board found for this project. Run Sprint Planning first.",
                    role="ScrumMaster"
                )
        
        # Calculate metrics
        metrics = board_tracker.get_metrics(project_id)
        
        # Get blocked task details
        blocked_details = self._get_blocked_details(board, tasks)
        
        # Get recently completed
        completed_details = self._get_completed_details(board, tasks)
        
        # Format sprint status
        sprint_status = f"""
- Progress: {metrics.progress_percent}%
- Points Completed: {metrics.points_completed}
- Points Remaining: {metrics.points_remaining}
"""
        
        # Generate standup report using LLM
        prompt = STANDUP_PROMPT.format(
            sprint_status=sprint_status,
            todo_count=len(board.todo),
            in_progress_count=len(board.in_progress),
            review_count=len(board.review),
            done_count=len(board.done),
            blocked_count=len(board.blocked),
            blocked_details=blocked_details or "No blocked tasks",
            completed_details=completed_details or "No recently completed tasks"
        )
        
        standup_report = await self._aask(prompt)
        
        # Create standup record
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        
        full_report = f"""# Daily Standup Report
**Date:** {timestamp}
**Project:** {project_id}

## Sprint Metrics
{sprint_status}

## Board Summary
| Status | Count |
|--------|-------|
| TODO | {len(board.todo)} |
| In Progress | {len(board.in_progress)} |
| Review | {len(board.review)} |
| Done | {len(board.done)} |
| Blocked | {len(board.blocked)} |

## Analysis
{standup_report}

---
*Report generated by ScrumMaster AI*
"""
        
        logger.info(f"Daily Standup completed for {project_id}")
        
        return Message(
            content=full_report,
            role="ScrumMaster",
            cause_by=self
        )
    
    def _get_blocked_details(self, board, tasks: Dict[str, Task]) -> str:
        """Get details of blocked tasks"""
        if not board.blocked:
            return ""
        
        lines = []
        for task_id in board.blocked:
            if task_id in tasks:
                task = tasks[task_id]
                deps = ", ".join(task.depends_on) if task.depends_on else "unknown"
                lines.append(f"- {task.title} (blocked by: {deps})")
        
        return "\n".join(lines)
    
    def _get_completed_details(self, board, tasks: Dict[str, Task]) -> str:
        """Get details of recently completed tasks"""
        if not board.done:
            return ""
        
        lines = []
        for task_id in board.done[-5:]:  # Last 5 completed
            if task_id in tasks:
                task = tasks[task_id]
                completed = task.completed_at.strftime("%Y-%m-%d") if task.completed_at else "N/A"
                lines.append(f"- {task.title} (completed: {completed})")
        
        return "\n".join(lines)
