#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@Time    : 2026/01/12
@Author  : MetaGPT-Pro Team
@File    : retrospective.py
@Desc    : Sprint Retrospective ceremony action - analyzes sprint and identifies improvements
"""
from typing import Dict, List, Optional
from datetime import datetime

from pydantic import Field

from metagpt.actions import Action
from metagpt.logs import logger
from metagpt.project.schemas import Task, TaskStatus, Sprint
from metagpt.project.backlog_manager import BacklogManager
from metagpt.project.board_tracker import board_tracker
from metagpt.schema import Message
from metagpt.tools.tool_registry import register_tool


RETROSPECTIVE_PROMPT = """
You are facilitating a Sprint Retrospective for Sprint {sprint_number}.

## Sprint Performance
{sprint_metrics}

## Velocity Trend
{velocity_info}

## Blockers Encountered
{blockers_summary}

## Task Flow Analysis
{flow_analysis}

As a Scrum Master, conduct a retrospective analysis:

1. **What went well?** - Identify successes and positive patterns
2. **What could be improved?** - Identify pain points and areas for improvement
3. **Action items** - Specific, actionable improvements for next sprint

Format as a structured retrospective report with clear action items.
"""


@register_tool(include_functions=["run"])
class RetrospectiveAction(Action):
    """Conducts Sprint Retrospective to identify improvements"""
    
    name: str = "Retrospective"
    desc: str = "Conduct Sprint Retrospective to analyze performance and identify improvements"
    
    async def run(
        self,
        project_id: str,
        sprint_number: int = 1,
        backlog_manager: Optional[BacklogManager] = None,
        **kwargs
    ) -> Message:
        """
        Conduct Sprint Retrospective ceremony.
        
        Args:
            project_id: The project identifier
            sprint_number: The sprint number to retrospect
            backlog_manager: Optional backlog manager instance
            
        Returns:
            Message containing retrospective results
        """
        logger.info(f"Starting Sprint Retrospective for Sprint {sprint_number}")
        
        # Load backlog manager
        if not backlog_manager:
            backlog_manager = BacklogManager(project_id)
            await backlog_manager.load()
        
        backlog = backlog_manager.get_backlog()
        sprints = await backlog_manager.load_sprints()
        
        if not sprints:
            return Message(
                content="No sprints found. Complete a sprint first.",
                role="ScrumMaster"
            )
        
        # Get the sprint to retrospect
        sprint = None
        for s in sprints:
            if s.number == sprint_number:
                sprint = s
                break
        
        if not sprint:
            sprint = sprints[-1]
        
        # Calculate metrics
        metrics = self._calculate_sprint_metrics(sprint, backlog)
        velocity_info = self._analyze_velocity(sprints, sprint_number)
        blockers_summary = self._analyze_blockers(sprint, backlog)
        flow_analysis = self._analyze_task_flow(sprint, backlog)
        
        # Generate retrospective using LLM
        prompt = RETROSPECTIVE_PROMPT.format(
            sprint_number=sprint_number,
            sprint_metrics=metrics,
            velocity_info=velocity_info,
            blockers_summary=blockers_summary,
            flow_analysis=flow_analysis
        )
        
        retro_analysis = await self._aask(prompt)
        
        # Create full retrospective report
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        
        full_report = f"""# Sprint {sprint_number} Retrospective
**Date:** {timestamp}
**Project:** {project_id}

## Sprint Metrics
{metrics}

## Velocity Analysis
{velocity_info}

## Blockers Summary
{blockers_summary}

## Task Flow
{flow_analysis}

---

## Retrospective Analysis

{retro_analysis}

---

## Next Sprint Recommendations
Based on this retrospective, the following improvements are recommended for Sprint {sprint_number + 1}:
1. Address identified blockers proactively
2. Adjust velocity expectations if needed
3. Implement process improvements from action items above

---
*Report generated by ScrumMaster AI*
"""
        
        logger.info(f"Sprint Retrospective completed for Sprint {sprint_number}")
        
        return Message(
            content=full_report,
            role="ScrumMaster",
            cause_by=self
        )
    
    def _calculate_sprint_metrics(self, sprint: Sprint, backlog) -> str:
        """Calculate key sprint metrics"""
        completed_tasks = []
        incomplete_tasks = []
        
        for task_id in sprint.tasks:
            if task_id in backlog.tasks:
                task = backlog.tasks[task_id]
                if task.status == TaskStatus.DONE:
                    completed_tasks.append(task)
                else:
                    incomplete_tasks.append(task)
        
        completed_points = sum(t.story_points for t in completed_tasks)
        planned_points = sprint.total_points
        completion_rate = (completed_points / planned_points * 100) if planned_points > 0 else 0
        
        return f"""
- **Planned Points:** {planned_points}
- **Completed Points:** {completed_points}
- **Velocity:** {completed_points} pts/sprint
- **Completion Rate:** {completion_rate:.1f}%
- **Tasks Completed:** {len(completed_tasks)} / {len(sprint.tasks)}
- **Carryover Tasks:** {len(incomplete_tasks)}
"""
    
    def _analyze_velocity(self, sprints: List[Sprint], current_sprint: int) -> str:
        """Analyze velocity trend across sprints"""
        if len(sprints) < 2:
            return "Not enough data for velocity trend analysis (first sprint)"
        
        velocities = []
        for s in sprints[:current_sprint]:
            velocities.append(s.completed_points)
        
        if not velocities:
            return "No velocity data available"
        
        avg_velocity = sum(velocities) / len(velocities)
        trend = "stable"
        if len(velocities) >= 2:
            if velocities[-1] > velocities[-2]:
                trend = "increasing ↑"
            elif velocities[-1] < velocities[-2]:
                trend = "decreasing ↓"
        
        return f"""
- **Average Velocity:** {avg_velocity:.1f} pts/sprint
- **Trend:** {trend}
- **History:** {', '.join(str(v) for v in velocities)} pts
"""
    
    def _analyze_blockers(self, sprint: Sprint, backlog) -> str:
        """Analyze blockers encountered during sprint"""
        blocked_tasks = []
        
        for task_id in sprint.tasks:
            if task_id in backlog.tasks:
                task = backlog.tasks[task_id]
                if task.status == TaskStatus.BLOCKED or task.depends_on:
                    blocked_tasks.append(task)
        
        if not blocked_tasks:
            return "No significant blockers encountered during this sprint."
        
        lines = [f"**{len(blocked_tasks)} tasks were blocked:**"]
        for task in blocked_tasks[:5]:  # Top 5
            deps = ", ".join(task.depends_on) if task.depends_on else "external"
            lines.append(f"- {task.title} (blocked by: {deps})")
        
        return "\n".join(lines)
    
    def _analyze_task_flow(self, sprint: Sprint, backlog) -> str:
        """Analyze task flow through the sprint"""
        status_counts = {status: 0 for status in TaskStatus}
        
        for task_id in sprint.tasks:
            if task_id in backlog.tasks:
                task = backlog.tasks[task_id]
                status_counts[task.status] += 1
        
        lines = ["**Final Task Distribution:**"]
        for status, count in status_counts.items():
            if count > 0:
                lines.append(f"- {status.value}: {count} tasks")
        
        return "\n".join(lines)
