llm:
  api_type: "openai"  # or azure / ollama / groq etc.
  base_url: "YOUR_BASE_URL"
  api_key: "YOUR_API_KEY"
  model: "gpt-4-turbo"  # or gpt-3.5-turbo
  proxy: "YOUR_PROXY"  # for LLM API requests
  # timeout: 600 # Optional. If set to 0, default value is 300.
  # Details: https://azure.microsoft.com/en-us/pricing/details/cognitive-services/openai-service/
  pricing_plan: "" # Optional. Use for Azure LLM when its model name is not the same as OpenAI's


# RAG Embedding.
# For backward compatibility, if the embedding is not set and the llm's api_type is either openai or azure, the llm's config will be used. 
embedding:
  api_type: "" # openai / azure / gemini / ollama etc. Check EmbeddingType for more options.
  base_url: ""
  api_key: ""
  model: ""
  api_version: ""
  embed_batch_size: 100

repair_llm_output: true  # when the output is not a valid json, try to repair it

proxy: "YOUR_PROXY"  # for tools like requests, playwright, selenium, etc.

search:
  api_type: "google"
  api_key: "YOUR_API_KEY"
  cse_id: "YOUR_CSE_ID"

browser:
  engine: "playwright"  # playwright/selenium
  browser_type: "chromium"  # playwright: chromium/firefox/webkit; selenium: chrome/firefox/edge/ie

mermaid:
  engine: "pyppeteer"
  path: "/Applications/Google Chrome.app"

redis:
  host: "YOUR_HOST"
  port: 32582
  password: "YOUR_PASSWORD"
  db: "0"

s3:
  access_key: "YOUR_ACCESS_KEY"
  secret_key: "YOUR_SECRET_KEY"
  endpoint: "YOUR_ENDPOINT"
  secure: false
  bucket: "test"

vault:
  metagpt_tti:
    values:
      url: "YOUR_URL"
    descriptions:
      url: "MetaGPT text to image REST API"
  sd_tti:
    values:
      url: "YOUR_URL"
    descriptions:
      url: "SD Engine URL"
  iflytek_tts:
    values:
      api_id: "YOUR_APP_ID"
      api_key: "YOUR_API_KEY"
      api_secret: "YOUR_API_SECRET"
    descriptions:
      api_id: "IFlyTek text to speech API ID"
      api_key: "IFlyTek text to speech API Key"
      api_secret: "IFlyTek text to speech API Secret"
  azure_tts:
    values:
      subscription_key: "YOUR_SUBSCRIPTION_KEY"
      region: "eastus"
    descriptions:
      subscription_key: "Azure text to speech subscription key"
      region: "Azure text to speech service region"
