####Provide LLM
####Currently support openai,claude,spark,zhipu,class openai
###Customize the LLM used by the role
ProductManager: Llama-2-13b-chat-hf
Architect: Llama-2-13b-chat-hf
ProjectManager: Llama-2-13b-chat-hf
Engineer: Llama-2-13b-chat-hf
#
####Customizing the LLM used by Action
WritePRD: Llama-2-13b-chat-hf
WriteDesign: deepseek-llm-67b-chat
WriteTasks: deepseek-llm-67b-chat
WriteCode: deepseek-llm-67b-chat
WriteCodeReview: deepseek-llm-67b-chat
#
#
####Customize LLM name and request address
MODEL_LIST:
  deepseek-llm-67b-chat:
    open_llm_api_base: "http://106.75.10.65:17866/v1"
  Llama-2-13b-chat-hf:
    open_llm_api_base: "http://106.75.10.65:17867/v1"